# Generated by Django 2.0 on 2019-07-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20190722_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imports',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
